name: Continous Integration
on:
  pull_request:
    branches: '**'
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "ðŸ’¡ The ${{ github.repository }} repository is now being fired up for testing."
      - uses: actions/checkout@v2
      - run: echo "Checkout Successful"
      - run: echo "Checking Linting"
      - uses: wearerequired/lint-action@v1
        with:
          eslint: true